#!/bin/bash
set -x
apt-get update -y
apt-get upgrade -y

apt-get install -y docker.io
sudo service docker start

#Add your user to the docker group to use Docker without administrator privileges
usermod -aG docker ubuntu

systemctl daemon-reload
systemctl restart docker

apt-get install -y python3-pip
docker pull jupyter/scipy-notebook

# mkdir -p /home/ubuntu/.jupyter
# echo "c.NotebookApp.password = 'sha1:58b675591ea72806c93a3a629c9881819ade05be'" > /home/ubuntu/.jupyter/jupyter_notebook_config.py

docker run -d -p 8888:8888 -v /home/ubuntu/.jupyter:/root/.jupyter jupyter/scipy-notebook

token=$(sudo docker logs $(sudo docker ps -q | head -n 1) 2>&1 | grep -o 'token=[^ ]*' | cut -d'=' -f2)

echo "Jupyter Notebook is running on http://$(curl -s http://checkip.amazonaws.com):8888/?token=$token"

